default:
	gcc P1_S.c -o P1_S
	gcc P2_S.c -o P2_S
	gcc P1_F.c -o P1_F
	gcc P2_F.c -o P2_F
	gcc P1_Q.c -o P1_Q
	gcc P2_Q.c -o P2_Q
socket:
	gcc P1_S.c -o P1_S
	gcc P2_S.c -o P2_S
fifo:
	gcc P1_F.c -o P1_F
	gcc P2_F.c -o P2_F
msgqueue:
	gcc P1_Q.c -o P1_Q
	gcc P2_Q.c -o P2_Q